- Cargo.toml
- src/lib.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/1)
> crate type and lint checks

- src/config.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/9)
> JSON base64 configuration

- src/launcher/mod.rs
- src/launcher/parser/dns/add_service_v1_0.rs
- src/launcher/parser/dns/mod.rs
- src/launcher/parser/dns/register_dns_v1_0.rs
- src/launcher/parser/mod.rs
- src/launcher/parser/nfs/create_dir_v1_0.rs
- src/launcher/parser/nfs/mod.rs
- src/launcher/parser/traits.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/10)
> design of JSON RPC dispatcher

- src/launcher/ipc_server/ipc_session/authenticate_app.rs
- src/launcher/parser/mod.rs
- src/launcher/parser/nfs/mod.rs
- src/macros.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/12)
> parse_result and parse_option

- src/errors.rs
- src/launcher/parser/helper.rs
- src/launcher/parser/mod.rs
- src/launcher/parser/nfs/create_dir_v1_0.rs
- src/launcher/parser/nfs/mod.rs
- src/launcher/parser/traits.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/13)
> task completed

- src/launcher/parser/nfs/create_dir_v1_0.rs
- src/launcher/parser/nfs/mod.rs
- src/launcher/parser/nfs/modify_dir_v1_0.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/14)
> slight approach change

- src/launcher/parser/nfs/create_dir_v1_0.rs
- src/launcher/parser/nfs/delete_dir_v1_0.rs
- src/launcher/parser/nfs/mod.rs
Delete directory integrated with nfs API. in create_directory `is_shared` variable updated as in RFC
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/15)
> MAID-1414 Delete directory

- src/launcher/parser/nfs/get_dir_v1_0.rs
- src/launcher/parser/nfs/get_file_v1_0.rs
- src/launcher/parser/nfs/mod.rs
- src/launcher/parser/nfs/modify_dir_v1_0.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/18)
> response layouts

- src/launcher/app_handler/mod.rs
- src/launcher/parser/nfs/delete_file_v1_0.rs
- src/launcher/parser/nfs/modify_file_v1_0.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/19)
> MAID-1418 Delete file implementation

- src/launcher/parser/helper.rs
- src/launcher/parser/nfs/create_file_v1_0.rs
- src/launcher/parser/nfs/mod.rs
Hello, I welcome any review comments for work done.
Please note i made a change to helper function tokenise_path to exclude strings that have '.' since assuming its a file name. Also assumed no directory path would contain a dot 
Bitcoin Address: 1JWJzJSYqau9MP6mfBpa5JogKU2giAWEn6
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/16)
> MAID-1417 Create file

- src/errors.rs
- src/launcher/app_handler/mod.rs
- src/launcher/ipc_server/events.rs
- src/launcher/ipc_server/ipc_session/events.rs
- src/launcher/ipc_server/ipc_session/mod.rs
- src/launcher/ipc_server/ipc_session/rsa_key_exchange.rs
- src/launcher/ipc_server/ipc_session/secure_communication.rs
- src/launcher/ipc_server/mod.rs
- src/lib.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/20)
> Secure communication start

- README.md
- src/errors.rs
- src/launcher/parser/dns/add_service_v1_0.rs
- src/launcher/parser/dns/mod.rs
- src/launcher/parser/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/21)
> Maid 1422 add Service

- src/launcher/parser/dns/mod.rs
- src/launcher/parser/dns/register_dns_v1_0.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/22)
> Maid 1421 register dns

- src/event_sender.rs
- src/ffi/implementation.rs
- src/launcher/app_handler/events.rs
- src/launcher/app_handler/mod.rs
- src/launcher/ipc_server/events.rs
- src/launcher/ipc_server/ipc_session/authenticate_app.rs
- src/launcher/ipc_server/ipc_session/mod.rs
- src/launcher/ipc_server/ipc_session/rsa_key_exchange.rs
- src/launcher/ipc_server/ipc_session/stream.rs
- src/launcher/ipc_server/mod.rs
- src/launcher/mod.rs
- src/launcher/parser/mod.rs
- src/launcher/parser/nfs/create_file_v1_0.rs
- src/launcher/parser/nfs/delete_file_v1_0.rs
- src/launcher/parser/nfs/get_dir_v1_0.rs
- src/launcher/parser/nfs/modify_file_v1_0.rs
- src/launcher/parser/test_utils.rs
- src/lib.rs
- src/observer.rs
<2> lints enabled
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/28)
> Documentation and Lints

- examples/event_loop.rs
- examples/launcher_cli.rs
- examples/self_auth.rs
- src/errors.rs
- src/launcher/app_handler/events.rs
- src/launcher/app_handler/misc.rs
- src/launcher/app_handler/mod.rs
- src/observer.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/31)
> MAID-1445 Task completed

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/32)
> Ticking TODOs

- src/config.rs
- src/errors.rs
- src/launcher/ipc_server/ipc_session/ecdh_key_exchange.rs
- src/launcher/ipc_server/ipc_session/mod.rs
- src/launcher/ipc_server/ipc_session/stream.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/34)
> restricting read payload size

- src/launcher/app_handler/mod.rs
- src/launcher/parser/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/35)
> Restricting launcher nonce to ASCII [48, 127] range

- examples/event_loop.rs
- examples/launcher_cli.rs
- src/config.rs
- src/errors.rs
- src/launcher/app_handler/misc.rs
- src/launcher/app_handler/mod.rs
- src/launcher/ipc_server/ipc_session/secure_communication.rs
- src/launcher/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/36)
> Local config file

- src/launcher/ipc_server/ipc_session/secure_communication.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/37)
> positive response

- src/launcher/ipc_server/ipc_session/secure_communication.rs
- src/launcher/parser/nfs/mod.rs
- src/launcher/parser/nfs/modify_dir_v1_0.rs
- src/launcher/parser/nfs/modify_file_v1_0.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/38)
> Using default parser

- src/launcher/parser/dns/add_service_v1_0.rs
- src/launcher/parser/dns/register_dns_v1_0.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/39)
> Add Service test

- src/launcher/ipc_server/ipc_session/secure_communication.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/40)
> improvement and todo

- src/launcher/app_handler/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/41)
> restricting string nonce to ASCII [48, 122]

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/43)
> Corrected link in README.md.

- src/launcher/app_handler/mod.rs
- src/launcher/mod.rs
- src/launcher/parser/dns/add_service_v1_0.rs
- src/launcher/parser/dns/register_dns_v1_0.rs
- src/launcher/parser/mod.rs
- src/launcher/parser/nfs/create_dir_v1_0.rs
- src/launcher/parser/nfs/create_file_v1_0.rs
- src/launcher/parser/nfs/delete_dir_v1_0.rs
- src/launcher/parser/nfs/delete_file_v1_0.rs
- src/launcher/parser/nfs/get_dir_v1_0.rs
- src/launcher/parser/nfs/get_file_v1_0.rs
- src/launcher/parser/nfs/modify_dir_v1_0.rs
- src/launcher/parser/nfs/modify_file_v1_0.rs
Modify File TODO addressed and removed `pub` from test cases
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/44)
> Todos fixes

- examples/event_loop.rs
- examples/launcher_cli.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/45)
> CLI improvement

- CHANGELOG.md
- Cargo.toml
- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/46)
> Version Change to 0.1.0

- CHANGELOG.md
- Cargo.toml
- src/launcher/ipc_server/ipc_session/mod.rs
- src/launcher/ipc_server/mod.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/50)
> Version change to 0.1.1

- examples/launcher_cli.rs
- src/lib.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/51)
> Remove lint and 100 character pernicketiness

- .gitignore
- app/app.html
- app/bower.json
- app/scripts/app.js
- app/scripts/controllers/auth_controller.js
- app/scripts/factories/auth_factory.js
- app/scripts/router.js
- app/stylesheets/basic.less
- app/stylesheets/buttons.less
- app/stylesheets/form.less
- app/stylesheets/frame.less
- app/stylesheets/list.less
- app/stylesheets/main.less
- app/stylesheets/mixins.less
- app/stylesheets/titlebar.less
- app/stylesheets/utils.less
- app/stylesheets/variables.less
- app/views/auth/register.html
- package.json
- tasks/build.js
- tasks/mocha-test.js
MAID-1554 UI conversion - Register page
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/59)
> MAID-1554 UI conversion - Register page

- app/app.html
- app/scripts/controllers/auth_controller.js
- app/scripts/controllers/user_controller.js
- app/scripts/directives/loader.js
- app/scripts/directives/switch.js
- app/scripts/factories/auth_factory.js
- app/scripts/factories/loader_factory.js
- app/stylesheets/buttons.less
- app/stylesheets/loader.less
- app/stylesheets/main.less
- app/views/components/loader.html
- app/views/components/switch.html
- app/views/user/manage_application.html
MAID-1558 List view HTML
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/65)
> MAID-1558 List view HTML

- app/UIUtils.js
- app/app.html
- app/app.js
- app/background.js
- app/images/close.svg
- app/package.json
- app/scripts/controllers/auth_controller.js
- app/scripts/controllers/user_controller.js
- app/scripts/factories/auth_factory.js
- app/scripts/factories/server_factory.js
- app/scripts/main.js
- app/server/boot.js
- app/server/controllers/auth.js
- app/stylesheets/basic.less
- app/stylesheets/buttons.less
- app/stylesheets/titlebar.less
MAID-1559 Window event handling
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/68)
> MAID-1559 Window event handling

- app/api/ffi/client.js
- app/app.html
- app/background.js
- app/scripts/controllers/auth_controller.js
- app/scripts/directives/loader.js
- app/server/boot.js
- app/server/controllers/auth.js
- app/server/model/session_info.js
- app/server/session_manager.js
- app/server/utils.js
- app/stylesheets/prompt.less
- app/views/components/prompt.html
- package.json
- tasks/mocha-test.js
- tests/auth.js
- tests/authorize.js
- tests/utils.js
MAID-1569 Authorisation test cases
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/70)
> MAID-1569 Authorisation test cases

- app/api/ffi/mod/nfs.js
- app/api/mod/nfs.js
- app/scripts/controllers/auth_controller.js
- app/server/controllers/nfs.js
- app/server/routes/version_one.js
- app/server/utils.js
MAID-1572 NFS API - Delete Directory
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/72)
> MAID-1572 NFS API - Delete Directory

- app/api/ffi/mod/nfs.js
- app/api/mod/nfs.js
- app/server/controllers/nfs.js
MAID-1571 Get directory fixes
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/74)
> MAID-1571 Get directory fixes

- app/api/ffi/mod/nfs.js
- app/api/mod/nfs.js
- app/server/controllers/auth.js
- app/server/controllers/nfs.js
- app/server/routes/version_one.js
MAID-1573 NFS API - Update Directory
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/75)
> MAID-1573 NFS API - Update Directory

- app/api/ffi/mod/nfs.js
- app/api/mod/nfs.js
- app/server/controllers/nfs.js
- app/server/routes/version_one.js
MAID-1574 NFS API - Create File
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/77)
> MAID-1574 NFS API - Create File

- app/api/ffi/mod/nfs.js
- app/api/mod/nfs.js
- app/server/controllers/nfs.js
- app/server/routes/version_one.js
MAID-1575 NFS API - Delete file
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/78)
> MAID-1575 NFS API - Delete file

- app/api/ffi/mod/nfs.js
- app/api/mod/nfs.js
- app/server/controllers/nfs.js
- app/server/routes/version_one.js
MAID-1577 NFS API - Update file metadata
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/80)
> MAID-1577 NFS API - Update file metadata

- app/api/ffi/mod/nfs.js
- app/api/mod/nfs.js
- app/server/boot.js
- app/server/controllers/nfs.js
- app/server/routes/version_one.js
- app/server/utils.js
MAID-1578 NFS API - Update File Content
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/82)
> MAID-1578 NFS API - Update File Content

- .travis.yml
- Cargo.toml
- examples/launcher_cli.rs
- src/lib.rs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/81)
> Add clippy, update lints and add nightly for travis.

- app/api/ffi/mod/dns.js
- app/api/ffi/mod/handler.js
- app/api/ffi/mod/nfs.js
- app/api/mod/dns.js
- app/api/safe.js
- app/server/controllers/dns.js
- app/server/controllers/nfs.js
- app/server/routes/version_one.js
MAID-1579 DNS API - Register DNS
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/84)
> MAID-1579 DNS API - Register DNS

- app/api/ffi/mod/dns.js
- app/api/ffi/mod/handler.js
- app/api/ffi/mod/nfs.js
- app/api/ffi/mod/util.js
- app/api/mod/dns.js
- app/api/safe.js
- app/server/controllers/dns.js
- app/server/controllers/nfs.js
- app/server/routes/version_one.js
MAID-1580 DNS API - Add Service
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/85)
> MAID-1580 DNS API - Add Service

- app/api/ffi/mod/dns.js
- app/api/ffi/mod/util.js
- app/api/mod/dns.js
- app/server/controllers/dns.js
- app/server/routes/version_one.js
MAID-1583 DNS API - Delete Long name
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/86)
> MAID-1583 DNS API - Delete Long name

- app/views/auth/register.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/92)
> Fix confirmPassword input

- app/app.html
- app/background.js
- app/stylesheets/frame.less
- app/stylesheets/prompt.less
- app/ui_utils.js
Application integrated with native frame.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/95)
> Application native frame integrated

- app/scripts/controllers/auth_controller.js
- app/scripts/directives/validateConfirmation.js
- app/scripts/directives/validateKeyword.js
- app/scripts/directives/validatePassword.js
- app/scripts/directives/validatePin.js
- app/ui_utils.js
- app/views/components/auth_loader.html
- app/views/user/manage_permissions.html
- app/views/user/settings.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/97)
> Text corrections

- app/views/auth/register.html
Registration page banner image removed
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/108)
> Registration page update

- app/scripts/controllers/basic_controller.js
- app/stylesheets/list.less
- app/views/auth/register.html
Registration loader issue fixed
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/109)
> Registration loader issue fixed

- app/api/ffi/mod/auth.js
- app/api/ffi/mod/handler.js
- app/api/mod/auth.js
- app/app.html
- app/app.js
- app/background.js
- app/scripts/constants.js
- app/scripts/controllers/auth_controller.js
- app/scripts/factories/server_factory.js
- app/scripts/main.js
- app/stylesheets/frame.less
- app/stylesheets/variables.less
- app/ui_utils.js
- app/views/components/status_bar.html
Handing networking state on UI
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/112)
> Handle network state

- CHANGELOG.MD
- app/api/ffi/mod/auth.js
- app/api/ffi/mod/handler.js
- app/api/mod/auth.js
- app/app.js
- app/bower.json
- app/package.json
- app/scripts/constants.js
- app/scripts/controllers/auth_controller.js
- app/scripts/controllers/user_controller.js
- app/scripts/factories/auth_factory.js
- app/scripts/factories/field_validator_factory.js
- app/server/model/permission.js
- app/stylesheets/form.less
- app/stylesheets/frame.less
- app/ui_utils.js
- app/views/auth/register.html
- app/views/components/auth_loader.html
Handle SAFE Drive error.
Authentication error message and style updated.
App permission bug fixed.
Drop client removed.
Registration banner integrated.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/113)
> Authentication module updated

- app/server/boot.js
CORS error for PUT request resolved
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/122)
> CORS error resolved for PUT request

- CHANGELOG.MD
- app/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/126)
> Version change to 0.4.2

- gulpfile.js
- package.json
- tasks/msvc_rebuild.js
- tasks/package.js
Packaging fixes and gulp task for MSVC rebuild
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/128)
> Packaging fixes and gulp task for MSVC rebuild 

- CHANGELOG.MD
- app/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/129)
> Version change to 0.4.3

- CHANGELOG.MD
- app/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/138)
> Version change to 0.4.4

- CHANGELOG.MD
- app/app.js
- app/package.json
- app/server/error_code_lookup.js
- config/env_production.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/143)
> Version change to 0.4.5

- app/app.js
- app/package.json
- app/server/error_code_lookup.js
- config/env_production.json
fs-extra and winston added to the app/package.json
error_code_lookup updated with the self_encryption error
Logger level set to debug in production mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/142)
> Version update to 0.4.5

- README.md
This adds license and contribution paragraphs to the README and also updates changed URLs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/145)
> docs/update: add more detail to README and update links

- CHANGELOG.MD
- app/package.json
Upgdate for safe_core v0.15.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/150)
> Version change to 0.4.6

- app/package.json
Version change to 0.0.1. This is just a sample PR for testing the ci deployment scripts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/157)
> Version change to 0.0.1

- app/server/boot.js
- app/server/controllers/auth.js
- app/server/controllers/dns.js
- app/server/controllers/nfs.js
- app/server/model/session_info.js
- app/server/utils.js
- tests/test_utils.js
Removed encryption/decryption from request/response.
Removed encryption/decryption from Test Cases request/response.
Request content-type can be any for requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/164)
> Removed encryption between Safe Launcher and Application

- app/api/ffi/client.js
- app/api/ffi/mod/auth.js
- app/api/ffi/mod/handler.js
- app/api/ffi/mod/util.js
- app/api/mod/auth.js
- app/app.js
- app/scripts/controllers/user_controller.js
- app/scripts/main.js
- app/server/boot.js
- app/server/controllers/dns.js
- app/server/controllers/nfs.js
- app/server/routes/version_0_5.js
- app/server/stream/dns_reader.js
- app/server/stream/nfs_reader.js
- app/server/stream/nfs_writer.js
- app/server/utils.js
- app/server/web_proxy.js
- app/ui_utils.js
- tests/nfs_dir_test.js
- tests/nfs_file_test.js
- tests/test_utils.js
API features based on the v0.5 RFC have been implemented.
Single client implementation after user authentication.
Multiple authorisation handled with queuing.
Network disconnect popup implemented.
Test cases updated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/165)
> Update API changes for v0.5

- app/api/ffi/client.js
- app/api/ffi/mod/dns.js
- app/api/ffi/mod/nfs.js
- app/api/ffi/mod/util.js
- app/api/mod/dns.js
- app/api/mod/nfs.js
- app/server/controllers/auth.js
- app/server/controllers/dns.js
- app/server/controllers/nfs.js
- app/server/error_code_lookup.js
- app/server/stream/dns_reader.js
- app/server/stream/nfs_reader.js
- app/server/web_proxy.js
- tests/nfs_file_test.js
- tests/test_utils.js
Empty file read and write operation
CORS and CSP fix in proxy
Added API for fetching file metadata
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/166)
> Resolve implementation bugs

- CHANGELOG.MD
- app/package.json
- NFS API updated with streaming
- CORS and CSP moved to proxy
- Single client handle
- Removed encryption and base64 conversion
- Error build script added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/170)
> version change to 0.5.0

- app/server/controllers/auth.js
- app/server/controllers/dns.js
- app/server/controllers/nfs.js
- app/server/stream/dns_reader.js
- app/server/stream/nfs_reader.js
- app/server/utils.js
- tests/dns_test.js
- tests/nfs_dir_test.js
- tests/nfs_file_test.js
Resolves file stream issue in dns getFile api. Refactored response handler and updated the responses to be send in json format through the handler.
DNS and NFS updated to use ResponseHandler from server/utils.js
Test cases updated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/172)
> fix/v0.5: resolve dns invalid file path error

- app/api/ffi/client.js
- app/app.js
- app/logger/log.js
- app/package.json
- app/scripts/main.js
- app/server/controllers/auth.js
- app/server/controllers/dns.js
- app/server/model/session_info.js
- app/server/utils.js
- appveyor.yml
- tests/test_utils.js
fixes #173
Logs cleaned up
Removed libsodium dependency
service and public name validation added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/174)
> fix/v0.5_patch: Resolve network connectivity status banner issue

- app/api/ffi/client.js
- app/api/ffi/mod/auth.js
- app/api/ffi/mod/nfs.js
- app/api/ffi/mod/util.js
- app/logger/log.js
- app/package.json
- app/scripts/constants.js
- package.json
- tasks/package.js
Fixes #177 
Application packaging issues fixed
Client handle creation failure notification to UI handled
Logger with time stamp and human readable file logging
Rust log file path issue sorted
Updated electron packager version
Login screen long message handled
validate isNull in FFI's execute for content request based on recent changes to safe_core
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/181)
> fix/packaging_and_logger: resolve binary name issue while packaging

- README.md
- app/server/routes/version_0_5.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/187)
> refactor/UI text: update the log strings

- CHANGELOG.MD
- app/package.json
- New Launcher UI with dashboard and log history
- NFS Create File API updated
- User credentials merged to a single input
- Proxy bug fixes
- FFI process restart issue fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/190)
> version change to 0.6.0

- app/app.html
Resolve authorisation loader issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/198)
> Resolve authorisation loader

- app/background.js
Browser icon property used to set the image
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/200)
> fix/app_icon: show application icon on linux

- app/background.js
App window size adjusted for windows platform
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/202)
> App window size adjusted for windows platform

- app/background.js
- app/stylesheets/base.less
- app/stylesheets/components.less
Window UI height issue fixed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/203)
> Window UI height issue fixed

- app/server/utils.js
Resolve header already sent issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/204)
> Resolve header already sent issue 

- CHANGELOG.MD
- app/package.json
- Authorisation now uses secret and password
- NFS modify file API is temporarily disabled
- until SequentialEncryptor can handle accepting offsets
- Persist user settings through sessions
- Log tab should have content ordered
- Create account UI updated
- Various bug fixes and UX updates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/207)
> Version change to 0.7.0

- app/api/ffi/mod/auth.js
- app/scripts/controllers/auth_controller.js
- app/scripts/factories/event_register.js
- app/scripts/router.js
- app/server/boot.js
- app/server/controllers/auth.js
- app/ui_utils.js
- app/views/auth/_acc_secret_form.html
- Handle error while preparing application root directory by propagating an failure event to the UI
- Map proper error messages for register and login failure
- ffi refactor for handling fetching safe drive key asynchrously
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/209)
> Patch fix for v0.7.0

- CHANGELOG.MD
- app/package.json
- Mapping registration and login with messages based on error codes
- Fetching app root directory failure case handled
- Stop proxy server on logout until unauthorised client is created
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/211)
> version change to 0.7.1

- app/background.js
Resolved grey background on application start up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/218)
> Resolved grey background on application start up

- README.md
- tasks/package.js
- tasks/utils.js
pass x86 or x64 argument while packaging. If no argument is passed the os.Arch() is used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/224)
> feat/pass_args_to_package: pass arch argument while packaging

- README.md
- app/api/ffi/mod/util.js
- app/app.html
- app/scripts/components/app_logs.js
- app/scripts/controllers/basic_controller.js
- app/scripts/controllers/dashboard_controller.js
- app/scripts/controllers/user_controller.js
- app/scripts/factories/event_register.js
- app/scripts/factories/log_list_bridge.js
- app/scripts/main.js
- app/stylesheets/buttons.less
- app/stylesheets/components.less
- app/views/tab/activity.html
- app/views/tab/help.html
- app/views/user/app_details.html
- app/views/user/app_list.html
- appveyor.yml
Use react setState for rendering logs
appveryor script updated
CI appveyor badge in readme updated
Help and demo app download link added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/226)
> refactor/log_list:refactor log list rendering

- CHANGELOG.MD
- app/package.json
- Set UI log file path from config handler
- DNS API - removed isPrivate param and replaced with rootPath
- NFS API - restrict root directory deletion
- Start up grey screen fixed
- Log list rendering optimisation
- API - ISO time format fix
- CSP header errors resolved
- Proxy hanging on application crash resolved
- Packaging fixes
- Minor style fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/228)
> version change to 0.8.0

- CHANGELOG.MD
- app/package.json
Revert "version change to 0.8.0"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/229)
> Revert version change to add missed out bugfix

- app/scripts/main.js
- app/server/controllers/auth.js
Clear application state on logout
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/230)
> fix/clear_app_state: clear application state

- app/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/238)
> Use correct reverse DNS identifier

- app/scripts/main.js
- app/server/controllers/dns.js
- app/server/controllers/nfs.js
- app/server/stream/nfs_writer.js
- app/ui_utils.js
Fix issues #234 #235 and #241
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/242)
> fix/ffi_crash: resolve issues #234 #235 and #241

- CHANGELOG.MD
- package.json
- Requires safe_core 0.20.0
- UI switched to React + Redux from angular
- FFI forked process is removed
- Basic API methods to work with low level DataTypes are added
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/251)
> Version change to 0.9.0

- app/ui/components/initial_settings.js
Updated routing from home to registration page after initial proxy setting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/252)
> Resolved routing issue after initial proxy setting

- README.md
- app/ffi/loader.js
- app/server/proxy_controller.js
- main.development.js
- package.js
- package.json
- rebuild_native.js
- webpack.config.base.js
- webpack.config.development.js
- webpack.config.production.js
Packaging scripts updated to package application as implemented during alpha-1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/254)
> fix/packaging: package application as in alpha-1

- .travis.yml
- README.md
- app/ffi/api/appendable_data.js
- app/ffi/api/nfs.js
- app/server/controllers/appendable_data.js
- app/server/controllers/data_id.js
- app/server/controllers/structured_data.js
- app/server/routes/version_0_5.js
- app/server/stream/dns_reader.js
- app/server/stream/nfs_reader.js
- app/server/utils.js
- app/ui/components/register_acc_pass_form.js
- main.development.js
Fixes
- DNS file read 
- Update Directory metadata
- low level apis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/259)
> fix/api:  v0.6 api fixes

- app/ffi/api/immutable_data.js
- app/server/controllers/appendable_data.js
- app/server/controllers/cipher_opts.js
- app/server/controllers/data_id.js
- app/server/controllers/immutable_data.js
- app/server/controllers/structured_data.js
- app/server/routes/version_0_5.js
- app/server/stream/immutable_data_reader.js
- app/server/stream/immutable_data_writer.js
- Immutable data api implemented
- Api bug fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/261)
> fix/api: refactor immutable data api

- CHANGELOG.MD
- README.md
- package.json
- Requires safe_core 0.21.2
- Web proxy removed
- Low level api updated to match one to one with safe_core
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/264)
> version change to 0.9.1

- app/ffi/api/appendable_data.js
- app/ffi/api/structured_data.js
- app/server/controllers/appendable_data.js
- app/server/controllers/structured_data.js
- app/server/routes/version_0_5.js
Read structured data by version.
Corrected type tags for Structured data.
Integrated Appendable data filter APIs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/maidsafe/safe_launcher/266)
> Updated structured data read and tag type and appendable data filter APIs

- app/ffi/api/appendable_data.js
- app/ffi/api/structured_data.js
- app/server/controllers/appendable_data.js
- app/server/controllers/immutable_data.js
- app/server/controllers/structured_data.js
- app/server/error_code_lookup.js
- app/server/routes/version_0_5.js
- app/server/stream/immutable_data_reader.js
- app/server/utils.js
New apis added
- Delete SD
- Make SD unclaimable
- validate size of SD
- validate size of AD
> feat/new_apis: expose sd delete apis

- CHANGELOG.MD
- README.md
- package.json
- Requires safe_core 0.22.0
- Versioned StructuredData API exposed to read a specific version
- StructuredData Delete APIs exposed
- API to validate size of StructuredData and ImmutableData added
- Minor bug fixes
> version change to 0.9.2

- app/ui/actions/auth_action.js
- app/ui/components/account_storage_chart.js
- app/ui/components/login.js
- app/ui/event_registry.js
- app/ui/reducers/user_reducer.js
Resolved dashboard update issue.
> MAID-1632 Launcher dashboard is not functional

- app/server/utils.js
- test/api/dns.spec.js
- test/api/structured_data.spec.js
Updated 404 error status for NoSuchData.
> MAID-1665 404 status must be sent from low level APIs

- app/ffi/api/appendable_data.js
- test/api/appendable_data.spec.js
- test/example.js
Resolved filterType enum issue.
> MAID-1636 Expose filterType in appendable data

- app/ffi/api/misc.js
- app/server/controllers/appendable_data.js
- app/server/routes/version_0_5.js
- package.json
- test/api/appendable_data.spec.js
- test/utils/appendable_data_utils.js
Integrated getSignKey feature to FFI, server and test.
> MAID-1667 Expose get user sign key API

- app/ffi/api/dns.js
- test/api/dns.spec.js
fixes #292 Handle incorrect service home directory path.
> MAID-1684 Fix launcher issue #292

- app/server/routes/version_0_5.js
- test/api/nfs_directory.spec.js
fixes #289 Updated directory path params as options in NFS get directory.
> MAID-1688 Fix launcher issue #289

- app/server/controllers/dns.js
- app/server/controllers/immutable_data.js
- app/server/controllers/nfs.js
- test/api/dns.spec.js
- test/api/immutable_data.spec.js
- test/api/nfs_file.spec.js
fixes #293 Resolved range error in reading NSF file, Immutable data and DNS file, if range end is higher than the file size.
> MAID-1710 Fix launcher issue #293

- app/ffi/api/dns.js
- app/ffi/api/nfs.js
- app/ffi/util/app_manager.js
- app/ffi/util/utils.js
- test/api/appendable_data.spec.js
- test/api/dns.spec.js
- test/api/immutable_data.spec.js
- test/api/nfs_directory.spec.js
- test/api/nfs_file.spec.js
- test/api/structured_data.spec.js
Improved test cases to check response parameters types.
> test/improved_test_cases: update test case for type check

- app/server/boot.js
- app/server/routes/version_0_6.js
- app/ui/components/register_acc_secret_form.js
fixes #285 Handled account already exist error on register failure on UI.
> Fix issue #285

- CHANGELOG.MD
- README.md
- package.json
> version change to 0.10.2

- CHANGELOG.MD
- README.md
- package.json
> version change to 0.10.3

- README.md
- app/ui/components/app_list.js
* added some links
* removed mention of a version of the Contributor Agreement
> MAID-2000: chore/readme: update README

- app/ui/components/login.js
- app/ui/components/register_invite_code_form.js
Resolved create account failure case bug.
> Create account failure fix

- app/ui/components/app_list.js
- app/ui/components/register_invite_code_form.js
Cleared cookies.
Updated demo app link.
> Clear cookies

- CHANGELOG.MD
- README.md
- package.json
- Invitation based create account
- Requires safe_core 0.23.0
> version change to 0.11.0
